### ISSUE TITLE
Passing across shared library boundary

### ISSUE THREAD

**Issue by nitro44x** [thelink2012/any#13]
It looks like the type checking is done by several function pointer comparisons (vtable). I've noticed that if I put a std::string in a linb::any in one dll, and try to extract it in another (even by reference), it always throws a bad_cast exception. 

Digging into it, it looks like the vtable pointers are set for the std::string in the dll that sets the linb::any, but when I try to cast the std::string out, it fails because it creatse a new vtable in the casting dll. 

Does it make sense to use type_info to compare types?

Update: I have not tested this in linux.

**Comment by thelink2012** [comment]
Oh. I was aware of such a issue and it did use `typeid`, but for some reason I didn't notice it getting completely removed by #11 (and follow-up commits a14cb3cb94e85cc4be58f3fbcb9c324cd9694f87 and ca5ed4ff185cfe88ba8c482cbf6466c6c94db850).

The solution is to restore  the `is_typed` method, but unlike before, it should only receive a typeid if `ANY_IMPL_NO_RTTI` is undefined. Additionally, restoring the `ANY_IMPL_FAST_TYPE_INFO_COMPARE` would be nice (in case RTTI is enabled).

Feel free to submit a patch. Otherwise, I'll look into it once I have the time.

**Comment by nitro44x** [comment]
Yup, that looks like the issue. I start working up a patch. Thanks for tracking it down.
